name: FET Loader CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    if: >
      !(github.event_name == 'push'
        && contains(github.event.head_commit.message, '[skip ci]'))
      && !(github.event_name == 'pull_request'
        && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name) 
    runs-on: windows-latest
    steps:
    - name: CI Notice
      run: |
        Invoke-WebRequest "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -Headers @{"Content-Type" = "application/json"} -body @{"chat_id" = "${{ secrets.CHAT_ID }}"; "text" = "<b>NEW PUSH IN clangremlini/fet-loader</b> | CI build started!"; "parse_mode" = "html"}
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        dir
        git submodule update --init --recursive
    - name: Install AHK
      uses: crazy-max/ghaction-chocolatey@v1.2.2
      with:
        args: install autohotkey.install --params='/DefaultVer:A32'
    - name: Build Loader
      run: ./COMPILE.bat
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - if: steps.build.outputs.status == 'failure'
      name: Failure Notice
      run: |
        Invoke-WebRequest "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -Headers @{"Content-Type" = "application/json"} -body @{"chat_id" = "${{ secrets.CHAT_ID }}"; "text" = "CI build on push in <code>clangremlini/fet-loader</code> <b>failed!</b>"; "parse_mode" = "html"}
        exit 1
    - if: steps.build.outputs.status != 'failure'
      name: Success Notice
      run: |
        Invoke-WebRequest "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" -Headers @{"Content-Type" = "application/json"} -body @{"chat_id" = "${{ secrets.CHAT_ID }}"; "text" = "CI build on push in <code>clangremlini/fet-loader</code> <b>passed!</b>"; "parse_mode" = "html"}
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: fet-loader
        path: loader.exe
